# docker-compose 파일은 해당 프로젝트를 위한 모든 configuration을 가지고 있다.

# docker-compose version
version: "3"

services:
  # 내 service의 이름, app. 지금은 이거 하나만 필요함
  app:
    # configuration의 build 섹션의 context를 .(=현재 디렉토리)으로
    build:
      context: .
    # "내 로컬 머신의 port를 8000으로, 내 이미지의 port를 8000으로"
    ports:
      - "8000:8000"
    # volume은 내가 만든 도커 이미지 안에서 리얼타임으로 업데이트 가능하게 함
    # 도커 이미지 configuration을 위한 nodemon 같은 것
    volumes:
      - ./app:/app

    # 앱을 실행하기 위한 command 설정
    # shell에서 command로 실행하겠다
    # 도커 이미지가 8000이기만 하면 모든 ip주소에서 run 가능

    #  sudo docker-compose run app sh -c "django-admin.py startproject app ." 으로 쟝고 프로젝트 시작
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
